import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LanguageCode = "en" | "hi" | "es" | "zh" | "ja" | "ko" | "de" | "fr" | "pt" | "ru" | "ar" | "tr";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.signals": "Signals",
    "nav.pricing": "Pricing",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.portfolio": "Portfolio",
    "nav.news": "News",
    "nav.history": "History Reminder",
    "nav.language": "Language",
    "nav.admin": "Admin Panel",
    "home.title": "CryptoBit",
    "home.subtitle": "Track cryptocurrency prices in real-time",
    "home.allAssets": "All Assets",
    "home.gainers": "Gainers",
    "home.losers": "Losers",
    "home.search": "Search coins...",
    "home.rank": "#",
    "home.name": "Name",
    "home.price": "Price",
    "home.change24h": "24h Change",
    "home.marketCap": "Market Cap",
    "home.previous": "Previous",
    "home.next": "Next",
    "home.page": "Page",
    "home.of": "of",
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Track your crypto holdings",
    "portfolio.addAsset": "Add Asset",
    "portfolio.totalValue": "Total Value",
    "portfolio.change24h": "24h Change",
    "portfolio.totalPnL": "Total Profit/Loss",
    "portfolio.yourHoldings": "Your Holdings",
    "portfolio.noAssets": "No assets yet",
    "portfolio.addFirst": "Start building your portfolio by adding your first crypto asset",
    "portfolio.addFirstAsset": "Add Your First Asset",
    "portfolio.editAsset": "Edit Asset",
    "portfolio.quantity": "Quantity",
    "portfolio.buyPrice": "Buy Price (USD)",
    "portfolio.cancel": "Cancel",
    "portfolio.save": "Save",
    "portfolio.saving": "Saving...",
    "portfolio.searchCoins": "Search coins...",
    "portfolio.loginRequired": "Login Required",
    "portfolio.loginToAccess": "Please login to access your portfolio",
    "portfolio.loginToContinue": "Login to Continue",
    "signals.title": "Trading Signals",
    "signals.subtitle": "Get professional trading signals",
    "signals.free": "Free Signals",
    "signals.pro": "Pro Signals",
    "signals.entry": "Entry",
    "signals.stopLoss": "Stop Loss",
    "signals.takeProfit": "Take Profit",
    "signals.leverage": "Leverage",
    "signals.upgradeToSee": "Upgrade to PRO to see this signal",
    "signals.noSignals": "No signals available",
    "pricing.title": "Upgrade to Pro",
    "pricing.subtitle": "Get access to premium trading signals",
    "pricing.perMonth": "/month",
    "pricing.features": "Features",
    "pricing.scanQR": "Scan QR to Pay",
    "pricing.uploadScreenshot": "Upload Payment Screenshot",
    "pricing.submit": "Submit Payment",
    "news.title": "Crypto News",
    "news.subtitle": "Latest cryptocurrency news and updates",
    "news.readMore": "Read More",
    "news.loading": "Loading news...",
    "news.noNews": "No news available",
    "language.title": "Language",
    "language.subtitle": "Choose your preferred language",
    "language.select": "Select Language",
    "language.save": "Save Language Preference",
    "language.saved": "Language preference saved!",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.retry": "Retry",
    "common.close": "Close",
    "auth.loginRequired": "Login Required",
    "auth.pleaseLogin": "Please login to continue",
  },
  hi: {
    "nav.home": "होम",
    "nav.signals": "सिग्नल",
    "nav.pricing": "मूल्य",
    "nav.login": "लॉगिन",
    "nav.logout": "लॉगआउट",
    "nav.portfolio": "पोर्टफोलियो",
    "nav.news": "समाचार",
    "nav.history": "इतिहास रिमाइंडर",
    "nav.language": "भाषा",
    "nav.admin": "एडमिन पैनल",
    "home.title": "क्रिप्टोबिट",
    "home.subtitle": "रीयल-टाइम में क्रिप्टोकरेंसी की कीमतें ट्रैक करें",
    "home.allAssets": "सभी संपत्तियां",
    "home.gainers": "बढ़ने वाले",
    "home.losers": "गिरने वाले",
    "home.search": "सिक्के खोजें...",
    "home.rank": "#",
    "home.name": "नाम",
    "home.price": "कीमत",
    "home.change24h": "24 घंटे का बदलाव",
    "home.marketCap": "मार्केट कैप",
    "home.previous": "पिछला",
    "home.next": "अगला",
    "home.page": "पृष्ठ",
    "home.of": "का",
    "portfolio.title": "पोर्टफोलियो",
    "portfolio.subtitle": "अपनी क्रिप्टो होल्डिंग्स ट्रैक करें",
    "portfolio.addAsset": "संपत्ति जोड़ें",
    "portfolio.totalValue": "कुल मूल्य",
    "portfolio.change24h": "24 घंटे का बदलाव",
    "portfolio.totalPnL": "कुल लाभ/हानि",
    "portfolio.yourHoldings": "आपकी होल्डिंग्स",
    "portfolio.noAssets": "अभी तक कोई संपत्ति नहीं",
    "portfolio.addFirst": "अपनी पहली क्रिप्टो संपत्ति जोड़कर अपना पोर्टफोलियो बनाना शुरू करें",
    "portfolio.addFirstAsset": "अपनी पहली संपत्ति जोड़ें",
    "portfolio.editAsset": "संपत्ति संपादित करें",
    "portfolio.quantity": "मात्रा",
    "portfolio.buyPrice": "खरीद मूल्य (USD)",
    "portfolio.cancel": "रद्द करें",
    "portfolio.save": "सहेजें",
    "portfolio.saving": "सहेजा जा रहा है...",
    "portfolio.searchCoins": "सिक्के खोजें...",
    "portfolio.loginRequired": "लॉगिन आवश्यक",
    "portfolio.loginToAccess": "अपने पोर्टफोलियो तक पहुंचने के लिए लॉगिन करें",
    "portfolio.loginToContinue": "जारी रखने के लिए लॉगिन करें",
    "signals.title": "ट्रेडिंग सिग्नल",
    "signals.subtitle": "पेशेवर ट्रेडिंग सिग्नल प्राप्त करें",
    "signals.free": "मुफ्त सिग्नल",
    "signals.pro": "प्रो सिग्नल",
    "signals.entry": "एंट्री",
    "signals.stopLoss": "स्टॉप लॉस",
    "signals.takeProfit": "टेक प्रॉफिट",
    "signals.leverage": "लीवरेज",
    "signals.upgradeToSee": "इस सिग्नल को देखने के लिए PRO में अपग्रेड करें",
    "signals.noSignals": "कोई सिग्नल उपलब्ध नहीं",
    "pricing.title": "प्रो में अपग्रेड करें",
    "pricing.subtitle": "प्रीमियम ट्रेडिंग सिग्नल तक पहुंच प्राप्त करें",
    "pricing.perMonth": "/महीना",
    "pricing.features": "विशेषताएं",
    "pricing.scanQR": "भुगतान के लिए QR स्कैन करें",
    "pricing.uploadScreenshot": "भुगतान स्क्रीनशॉट अपलोड करें",
    "pricing.submit": "भुगतान जमा करें",
    "news.title": "क्रिप्टो समाचार",
    "news.subtitle": "नवीनतम क्रिप्टोकरेंसी समाचार और अपडेट",
    "news.readMore": "और पढ़ें",
    "news.loading": "समाचार लोड हो रहे हैं...",
    "news.noNews": "कोई समाचार उपलब्ध नहीं",
    "language.title": "भाषा",
    "language.subtitle": "अपनी पसंदीदा भाषा चुनें",
    "language.select": "भाषा चुनें",
    "language.save": "भाषा प्राथमिकता सहेजें",
    "language.saved": "भाषा प्राथमिकता सहेजी गई!",
    "common.loading": "लोड हो रहा है...",
    "common.error": "एक त्रुटि हुई",
    "common.retry": "पुनः प्रयास करें",
    "common.close": "बंद करें",
    "auth.loginRequired": "लॉगिन आवश्यक",
    "auth.pleaseLogin": "जारी रखने के लिए लॉगिन करें",
  },
  es: {
    "nav.home": "Inicio",
    "nav.signals": "Señales",
    "nav.pricing": "Precios",
    "nav.login": "Iniciar sesión",
    "nav.logout": "Cerrar sesión",
    "nav.portfolio": "Portafolio",
    "nav.news": "Noticias",
    "nav.history": "Recordatorio Histórico",
    "nav.language": "Idioma",
    "nav.admin": "Panel de Admin",
    "home.title": "CryptoBit",
    "home.subtitle": "Rastrea precios de criptomonedas en tiempo real",
    "home.allAssets": "Todos los Activos",
    "home.gainers": "Ganadores",
    "home.losers": "Perdedores",
    "home.search": "Buscar monedas...",
    "home.rank": "#",
    "home.name": "Nombre",
    "home.price": "Precio",
    "home.change24h": "Cambio 24h",
    "home.marketCap": "Cap. de Mercado",
    "home.previous": "Anterior",
    "home.next": "Siguiente",
    "home.page": "Página",
    "home.of": "de",
    "portfolio.title": "Portafolio",
    "portfolio.subtitle": "Rastrea tus criptoactivos",
    "portfolio.addAsset": "Agregar Activo",
    "portfolio.totalValue": "Valor Total",
    "portfolio.change24h": "Cambio 24h",
    "portfolio.totalPnL": "Ganancia/Pérdida Total",
    "portfolio.yourHoldings": "Tus Activos",
    "portfolio.noAssets": "Sin activos aún",
    "portfolio.addFirst": "Comienza a construir tu portafolio agregando tu primer criptoactivo",
    "portfolio.addFirstAsset": "Agregar Tu Primer Activo",
    "portfolio.editAsset": "Editar Activo",
    "portfolio.quantity": "Cantidad",
    "portfolio.buyPrice": "Precio de Compra (USD)",
    "portfolio.cancel": "Cancelar",
    "portfolio.save": "Guardar",
    "portfolio.saving": "Guardando...",
    "portfolio.searchCoins": "Buscar monedas...",
    "portfolio.loginRequired": "Inicio de Sesión Requerido",
    "portfolio.loginToAccess": "Inicia sesión para acceder a tu portafolio",
    "portfolio.loginToContinue": "Iniciar Sesión",
    "signals.title": "Señales de Trading",
    "signals.subtitle": "Obtén señales profesionales de trading",
    "signals.free": "Señales Gratis",
    "signals.pro": "Señales Pro",
    "signals.entry": "Entrada",
    "signals.stopLoss": "Stop Loss",
    "signals.takeProfit": "Take Profit",
    "signals.leverage": "Apalancamiento",
    "signals.upgradeToSee": "Actualiza a PRO para ver esta señal",
    "signals.noSignals": "No hay señales disponibles",
    "pricing.title": "Actualizar a Pro",
    "pricing.subtitle": "Obtén acceso a señales premium",
    "pricing.perMonth": "/mes",
    "pricing.features": "Características",
    "pricing.scanQR": "Escanea QR para Pagar",
    "pricing.uploadScreenshot": "Subir Captura de Pago",
    "pricing.submit": "Enviar Pago",
    "news.title": "Noticias Crypto",
    "news.subtitle": "Últimas noticias y actualizaciones",
    "news.readMore": "Leer Más",
    "news.loading": "Cargando noticias...",
    "news.noNews": "No hay noticias disponibles",
    "language.title": "Idioma",
    "language.subtitle": "Elige tu idioma preferido",
    "language.select": "Seleccionar Idioma",
    "language.save": "Guardar Preferencia",
    "language.saved": "¡Preferencia de idioma guardada!",
    "common.loading": "Cargando...",
    "common.error": "Ocurrió un error",
    "common.retry": "Reintentar",
    "common.close": "Cerrar",
    "auth.loginRequired": "Inicio de Sesión Requerido",
    "auth.pleaseLogin": "Inicia sesión para continuar",
  },
  zh: {
    "nav.home": "首页",
    "nav.signals": "信号",
    "nav.pricing": "价格",
    "nav.login": "登录",
    "nav.logout": "登出",
    "nav.portfolio": "投资组合",
    "nav.news": "新闻",
    "nav.history": "历史提醒",
    "nav.language": "语言",
    "nav.admin": "管理面板",
    "home.title": "CryptoBit",
    "home.subtitle": "实时追踪加密货币价格",
    "home.allAssets": "所有资产",
    "home.gainers": "涨幅榜",
    "home.losers": "跌幅榜",
    "home.search": "搜索币种...",
    "home.rank": "#",
    "home.name": "名称",
    "home.price": "价格",
    "home.change24h": "24小时变化",
    "home.marketCap": "市值",
    "home.previous": "上一页",
    "home.next": "下一页",
    "home.page": "第",
    "home.of": "页，共",
    "portfolio.title": "投资组合",
    "portfolio.subtitle": "追踪您的加密货币持仓",
    "portfolio.addAsset": "添加资产",
    "portfolio.totalValue": "总价值",
    "portfolio.change24h": "24小时变化",
    "portfolio.totalPnL": "总盈亏",
    "portfolio.yourHoldings": "您的持仓",
    "portfolio.noAssets": "暂无资产",
    "portfolio.addFirst": "添加您的第一个加密资产来构建投资组合",
    "portfolio.addFirstAsset": "添加第一个资产",
    "portfolio.editAsset": "编辑资产",
    "portfolio.quantity": "数量",
    "portfolio.buyPrice": "买入价格 (USD)",
    "portfolio.cancel": "取消",
    "portfolio.save": "保存",
    "portfolio.saving": "保存中...",
    "portfolio.searchCoins": "搜索币种...",
    "portfolio.loginRequired": "需要登录",
    "portfolio.loginToAccess": "请登录以访问您的投资组合",
    "portfolio.loginToContinue": "登录继续",
    "signals.title": "交易信号",
    "signals.subtitle": "获取专业交易信号",
    "signals.free": "免费信号",
    "signals.pro": "专业信号",
    "signals.entry": "入场价",
    "signals.stopLoss": "止损",
    "signals.takeProfit": "止盈",
    "signals.leverage": "杠杆",
    "signals.upgradeToSee": "升级到PRO查看此信号",
    "signals.noSignals": "暂无信号",
    "pricing.title": "升级到专业版",
    "pricing.subtitle": "获取高级交易信号",
    "pricing.perMonth": "/月",
    "pricing.features": "功能",
    "pricing.scanQR": "扫描二维码支付",
    "pricing.uploadScreenshot": "上传支付截图",
    "pricing.submit": "提交支付",
    "news.title": "加密货币新闻",
    "news.subtitle": "最新加密货币新闻和更新",
    "news.readMore": "阅读更多",
    "news.loading": "加载新闻中...",
    "news.noNews": "暂无新闻",
    "language.title": "语言",
    "language.subtitle": "选择您的首选语言",
    "language.select": "选择语言",
    "language.save": "保存语言偏好",
    "language.saved": "语言偏好已保存！",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.retry": "重试",
    "common.close": "关闭",
    "auth.loginRequired": "需要登录",
    "auth.pleaseLogin": "请登录以继续",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.signals": "シグナル",
    "nav.pricing": "料金",
    "nav.login": "ログイン",
    "nav.logout": "ログアウト",
    "nav.portfolio": "ポートフォリオ",
    "nav.news": "ニュース",
    "nav.history": "履歴リマインダー",
    "nav.language": "言語",
    "nav.admin": "管理パネル",
    "home.title": "CryptoBit",
    "home.subtitle": "リアルタイムで暗号通貨の価格を追跡",
    "home.allAssets": "すべての資産",
    "home.gainers": "上昇銘柄",
    "home.losers": "下落銘柄",
    "home.search": "コインを検索...",
    "home.rank": "#",
    "home.name": "名前",
    "home.price": "価格",
    "home.change24h": "24時間変動",
    "home.marketCap": "時価総額",
    "home.previous": "前へ",
    "home.next": "次へ",
    "home.page": "ページ",
    "home.of": "/",
    "portfolio.title": "ポートフォリオ",
    "portfolio.subtitle": "暗号資産の保有を追跡",
    "portfolio.addAsset": "資産を追加",
    "portfolio.totalValue": "総額",
    "portfolio.change24h": "24時間変動",
    "portfolio.totalPnL": "総損益",
    "portfolio.yourHoldings": "保有資産",
    "portfolio.noAssets": "資産がありません",
    "portfolio.addFirst": "最初の暗号資産を追加してポートフォリオを構築",
    "portfolio.addFirstAsset": "最初の資産を追加",
    "portfolio.editAsset": "資産を編集",
    "portfolio.quantity": "数量",
    "portfolio.buyPrice": "購入価格 (USD)",
    "portfolio.cancel": "キャンセル",
    "portfolio.save": "保存",
    "portfolio.saving": "保存中...",
    "portfolio.searchCoins": "コインを検索...",
    "portfolio.loginRequired": "ログインが必要",
    "portfolio.loginToAccess": "ポートフォリオにアクセスするにはログインしてください",
    "portfolio.loginToContinue": "ログインして続行",
    "signals.title": "取引シグナル",
    "signals.subtitle": "プロの取引シグナルを取得",
    "signals.free": "無料シグナル",
    "signals.pro": "プロシグナル",
    "signals.entry": "エントリー",
    "signals.stopLoss": "ストップロス",
    "signals.takeProfit": "テイクプロフィット",
    "signals.leverage": "レバレッジ",
    "signals.upgradeToSee": "このシグナルを見るにはPROにアップグレード",
    "signals.noSignals": "シグナルがありません",
    "pricing.title": "プロにアップグレード",
    "pricing.subtitle": "プレミアム取引シグナルへのアクセスを取得",
    "pricing.perMonth": "/月",
    "pricing.features": "機能",
    "pricing.scanQR": "QRをスキャンして支払い",
    "pricing.uploadScreenshot": "支払いスクリーンショットをアップロード",
    "pricing.submit": "支払いを送信",
    "news.title": "暗号ニュース",
    "news.subtitle": "最新の暗号通貨ニュースとアップデート",
    "news.readMore": "続きを読む",
    "news.loading": "ニュースを読み込み中...",
    "news.noNews": "ニュースがありません",
    "language.title": "言語",
    "language.subtitle": "お好みの言語を選択",
    "language.select": "言語を選択",
    "language.save": "言語設定を保存",
    "language.saved": "言語設定が保存されました！",
    "common.loading": "読み込み中...",
    "common.error": "エラーが発生しました",
    "common.retry": "再試行",
    "common.close": "閉じる",
    "auth.loginRequired": "ログインが必要",
    "auth.pleaseLogin": "続行するにはログインしてください",
  },
  ko: {
    "nav.home": "홈",
    "nav.signals": "신호",
    "nav.pricing": "가격",
    "nav.login": "로그인",
    "nav.logout": "로그아웃",
    "nav.portfolio": "포트폴리오",
    "nav.news": "뉴스",
    "nav.history": "기록 알림",
    "nav.language": "언어",
    "nav.admin": "관리 패널",
    "home.title": "CryptoBit",
    "home.subtitle": "실시간으로 암호화폐 가격 추적",
    "home.allAssets": "모든 자산",
    "home.gainers": "상승",
    "home.losers": "하락",
    "home.search": "코인 검색...",
    "home.rank": "#",
    "home.name": "이름",
    "home.price": "가격",
    "home.change24h": "24시간 변동",
    "home.marketCap": "시가총액",
    "home.previous": "이전",
    "home.next": "다음",
    "home.page": "페이지",
    "home.of": "/",
    "portfolio.title": "포트폴리오",
    "portfolio.subtitle": "암호화폐 보유량 추적",
    "portfolio.addAsset": "자산 추가",
    "portfolio.totalValue": "총 가치",
    "portfolio.change24h": "24시간 변동",
    "portfolio.totalPnL": "총 손익",
    "portfolio.yourHoldings": "보유 자산",
    "portfolio.noAssets": "자산 없음",
    "portfolio.addFirst": "첫 번째 암호화폐를 추가하여 포트폴리오 구축 시작",
    "portfolio.addFirstAsset": "첫 자산 추가",
    "portfolio.editAsset": "자산 편집",
    "portfolio.quantity": "수량",
    "portfolio.buyPrice": "구매 가격 (USD)",
    "portfolio.cancel": "취소",
    "portfolio.save": "저장",
    "portfolio.saving": "저장 중...",
    "portfolio.searchCoins": "코인 검색...",
    "portfolio.loginRequired": "로그인 필요",
    "portfolio.loginToAccess": "포트폴리오에 접근하려면 로그인하세요",
    "portfolio.loginToContinue": "로그인하여 계속",
    "signals.title": "거래 신호",
    "signals.subtitle": "전문 거래 신호 받기",
    "signals.free": "무료 신호",
    "signals.pro": "프로 신호",
    "signals.entry": "진입",
    "signals.stopLoss": "손절",
    "signals.takeProfit": "익절",
    "signals.leverage": "레버리지",
    "signals.upgradeToSee": "이 신호를 보려면 PRO로 업그레이드",
    "signals.noSignals": "신호 없음",
    "pricing.title": "프로로 업그레이드",
    "pricing.subtitle": "프리미엄 거래 신호 접근",
    "pricing.perMonth": "/월",
    "pricing.features": "기능",
    "pricing.scanQR": "QR 스캔하여 결제",
    "pricing.uploadScreenshot": "결제 스크린샷 업로드",
    "pricing.submit": "결제 제출",
    "news.title": "암호화폐 뉴스",
    "news.subtitle": "최신 암호화폐 뉴스 및 업데이트",
    "news.readMore": "더 읽기",
    "news.loading": "뉴스 로딩 중...",
    "news.noNews": "뉴스 없음",
    "language.title": "언어",
    "language.subtitle": "선호하는 언어 선택",
    "language.select": "언어 선택",
    "language.save": "언어 설정 저장",
    "language.saved": "언어 설정이 저장되었습니다!",
    "common.loading": "로딩 중...",
    "common.error": "오류가 발생했습니다",
    "common.retry": "재시도",
    "common.close": "닫기",
    "auth.loginRequired": "로그인 필요",
    "auth.pleaseLogin": "계속하려면 로그인하세요",
  },
  de: {
    "nav.home": "Startseite",
    "nav.signals": "Signale",
    "nav.pricing": "Preise",
    "nav.login": "Anmelden",
    "nav.logout": "Abmelden",
    "nav.portfolio": "Portfolio",
    "nav.news": "Nachrichten",
    "nav.history": "Verlaufserinnerung",
    "nav.language": "Sprache",
    "nav.admin": "Admin-Panel",
    "home.title": "CryptoBit",
    "home.subtitle": "Verfolgen Sie Kryptowährungspreise in Echtzeit",
    "home.allAssets": "Alle Vermögenswerte",
    "home.gainers": "Gewinner",
    "home.losers": "Verlierer",
    "home.search": "Münzen suchen...",
    "home.rank": "#",
    "home.name": "Name",
    "home.price": "Preis",
    "home.change24h": "24h Änderung",
    "home.marketCap": "Marktkapitalisierung",
    "home.previous": "Zurück",
    "home.next": "Weiter",
    "home.page": "Seite",
    "home.of": "von",
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Verfolgen Sie Ihre Krypto-Bestände",
    "portfolio.addAsset": "Vermögenswert hinzufügen",
    "portfolio.totalValue": "Gesamtwert",
    "portfolio.change24h": "24h Änderung",
    "portfolio.totalPnL": "Gesamtgewinn/-verlust",
    "portfolio.yourHoldings": "Ihre Bestände",
    "portfolio.noAssets": "Noch keine Vermögenswerte",
    "portfolio.addFirst": "Beginnen Sie mit dem Aufbau Ihres Portfolios",
    "portfolio.addFirstAsset": "Ersten Vermögenswert hinzufügen",
    "portfolio.editAsset": "Vermögenswert bearbeiten",
    "portfolio.quantity": "Menge",
    "portfolio.buyPrice": "Kaufpreis (USD)",
    "portfolio.cancel": "Abbrechen",
    "portfolio.save": "Speichern",
    "portfolio.saving": "Speichern...",
    "portfolio.searchCoins": "Münzen suchen...",
    "portfolio.loginRequired": "Anmeldung erforderlich",
    "portfolio.loginToAccess": "Melden Sie sich an, um auf Ihr Portfolio zuzugreifen",
    "portfolio.loginToContinue": "Anmelden zum Fortfahren",
    "signals.title": "Handelssignale",
    "signals.subtitle": "Erhalten Sie professionelle Handelssignale",
    "signals.free": "Kostenlose Signale",
    "signals.pro": "Pro-Signale",
    "signals.entry": "Einstieg",
    "signals.stopLoss": "Stop-Loss",
    "signals.takeProfit": "Take-Profit",
    "signals.leverage": "Hebel",
    "signals.upgradeToSee": "Upgrade auf PRO, um dieses Signal zu sehen",
    "signals.noSignals": "Keine Signale verfügbar",
    "pricing.title": "Upgrade auf Pro",
    "pricing.subtitle": "Erhalten Sie Zugang zu Premium-Signalen",
    "pricing.perMonth": "/Monat",
    "pricing.features": "Funktionen",
    "pricing.scanQR": "QR zum Bezahlen scannen",
    "pricing.uploadScreenshot": "Zahlungsscreenshot hochladen",
    "pricing.submit": "Zahlung einreichen",
    "news.title": "Krypto-Nachrichten",
    "news.subtitle": "Neueste Krypto-Nachrichten und Updates",
    "news.readMore": "Mehr lesen",
    "news.loading": "Nachrichten werden geladen...",
    "news.noNews": "Keine Nachrichten verfügbar",
    "language.title": "Sprache",
    "language.subtitle": "Wählen Sie Ihre bevorzugte Sprache",
    "language.select": "Sprache auswählen",
    "language.save": "Spracheinstellung speichern",
    "language.saved": "Spracheinstellung gespeichert!",
    "common.loading": "Laden...",
    "common.error": "Ein Fehler ist aufgetreten",
    "common.retry": "Wiederholen",
    "common.close": "Schließen",
    "auth.loginRequired": "Anmeldung erforderlich",
    "auth.pleaseLogin": "Bitte melden Sie sich an, um fortzufahren",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.signals": "Signaux",
    "nav.pricing": "Tarifs",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "nav.portfolio": "Portefeuille",
    "nav.news": "Actualités",
    "nav.history": "Rappel Historique",
    "nav.language": "Langue",
    "nav.admin": "Panneau Admin",
    "home.title": "CryptoBit",
    "home.subtitle": "Suivez les prix des cryptomonnaies en temps réel",
    "home.allAssets": "Tous les Actifs",
    "home.gainers": "Gagnants",
    "home.losers": "Perdants",
    "home.search": "Rechercher...",
    "home.rank": "#",
    "home.name": "Nom",
    "home.price": "Prix",
    "home.change24h": "Variation 24h",
    "home.marketCap": "Cap. Marché",
    "home.previous": "Précédent",
    "home.next": "Suivant",
    "home.page": "Page",
    "home.of": "sur",
    "portfolio.title": "Portefeuille",
    "portfolio.subtitle": "Suivez vos avoirs crypto",
    "portfolio.addAsset": "Ajouter un Actif",
    "portfolio.totalValue": "Valeur Totale",
    "portfolio.change24h": "Variation 24h",
    "portfolio.totalPnL": "Profit/Perte Total",
    "portfolio.yourHoldings": "Vos Avoirs",
    "portfolio.noAssets": "Pas encore d'actifs",
    "portfolio.addFirst": "Commencez à construire votre portefeuille",
    "portfolio.addFirstAsset": "Ajouter Votre Premier Actif",
    "portfolio.editAsset": "Modifier l'Actif",
    "portfolio.quantity": "Quantité",
    "portfolio.buyPrice": "Prix d'Achat (USD)",
    "portfolio.cancel": "Annuler",
    "portfolio.save": "Enregistrer",
    "portfolio.saving": "Enregistrement...",
    "portfolio.searchCoins": "Rechercher...",
    "portfolio.loginRequired": "Connexion Requise",
    "portfolio.loginToAccess": "Connectez-vous pour accéder à votre portefeuille",
    "portfolio.loginToContinue": "Se Connecter",
    "signals.title": "Signaux de Trading",
    "signals.subtitle": "Obtenez des signaux professionnels",
    "signals.free": "Signaux Gratuits",
    "signals.pro": "Signaux Pro",
    "signals.entry": "Entrée",
    "signals.stopLoss": "Stop Loss",
    "signals.takeProfit": "Take Profit",
    "signals.leverage": "Effet de Levier",
    "signals.upgradeToSee": "Passez à PRO pour voir ce signal",
    "signals.noSignals": "Aucun signal disponible",
    "pricing.title": "Passer à Pro",
    "pricing.subtitle": "Accédez aux signaux premium",
    "pricing.perMonth": "/mois",
    "pricing.features": "Fonctionnalités",
    "pricing.scanQR": "Scanner le QR pour Payer",
    "pricing.uploadScreenshot": "Télécharger la Capture de Paiement",
    "pricing.submit": "Soumettre le Paiement",
    "news.title": "Actualités Crypto",
    "news.subtitle": "Dernières nouvelles et mises à jour",
    "news.readMore": "Lire Plus",
    "news.loading": "Chargement des actualités...",
    "news.noNews": "Aucune actualité disponible",
    "language.title": "Langue",
    "language.subtitle": "Choisissez votre langue préférée",
    "language.select": "Sélectionner la Langue",
    "language.save": "Enregistrer la Préférence",
    "language.saved": "Préférence de langue enregistrée !",
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.retry": "Réessayer",
    "common.close": "Fermer",
    "auth.loginRequired": "Connexion Requise",
    "auth.pleaseLogin": "Veuillez vous connecter pour continuer",
  },
  pt: {
    "nav.home": "Início",
    "nav.signals": "Sinais",
    "nav.pricing": "Preços",
    "nav.login": "Entrar",
    "nav.logout": "Sair",
    "nav.portfolio": "Portfólio",
    "nav.news": "Notícias",
    "nav.history": "Lembrete Histórico",
    "nav.language": "Idioma",
    "nav.admin": "Painel Admin",
    "home.title": "CryptoBit",
    "home.subtitle": "Acompanhe preços de criptomoedas em tempo real",
    "home.allAssets": "Todos os Ativos",
    "home.gainers": "Em Alta",
    "home.losers": "Em Baixa",
    "home.search": "Pesquisar moedas...",
    "home.rank": "#",
    "home.name": "Nome",
    "home.price": "Preço",
    "home.change24h": "Variação 24h",
    "home.marketCap": "Cap. de Mercado",
    "home.previous": "Anterior",
    "home.next": "Próximo",
    "home.page": "Página",
    "home.of": "de",
    "portfolio.title": "Portfólio",
    "portfolio.subtitle": "Acompanhe seus ativos cripto",
    "portfolio.addAsset": "Adicionar Ativo",
    "portfolio.totalValue": "Valor Total",
    "portfolio.change24h": "Variação 24h",
    "portfolio.totalPnL": "Lucro/Prejuízo Total",
    "portfolio.yourHoldings": "Seus Ativos",
    "portfolio.noAssets": "Nenhum ativo ainda",
    "portfolio.addFirst": "Comece a construir seu portfólio",
    "portfolio.addFirstAsset": "Adicionar Primeiro Ativo",
    "portfolio.editAsset": "Editar Ativo",
    "portfolio.quantity": "Quantidade",
    "portfolio.buyPrice": "Preço de Compra (USD)",
    "portfolio.cancel": "Cancelar",
    "portfolio.save": "Salvar",
    "portfolio.saving": "Salvando...",
    "portfolio.searchCoins": "Pesquisar moedas...",
    "portfolio.loginRequired": "Login Necessário",
    "portfolio.loginToAccess": "Faça login para acessar seu portfólio",
    "portfolio.loginToContinue": "Fazer Login",
    "signals.title": "Sinais de Trading",
    "signals.subtitle": "Obtenha sinais profissionais",
    "signals.free": "Sinais Grátis",
    "signals.pro": "Sinais Pro",
    "signals.entry": "Entrada",
    "signals.stopLoss": "Stop Loss",
    "signals.takeProfit": "Take Profit",
    "signals.leverage": "Alavancagem",
    "signals.upgradeToSee": "Atualize para PRO para ver este sinal",
    "signals.noSignals": "Nenhum sinal disponível",
    "pricing.title": "Atualizar para Pro",
    "pricing.subtitle": "Obtenha acesso a sinais premium",
    "pricing.perMonth": "/mês",
    "pricing.features": "Recursos",
    "pricing.scanQR": "Escaneie o QR para Pagar",
    "pricing.uploadScreenshot": "Enviar Captura de Pagamento",
    "pricing.submit": "Enviar Pagamento",
    "news.title": "Notícias Cripto",
    "news.subtitle": "Últimas notícias e atualizações",
    "news.readMore": "Ler Mais",
    "news.loading": "Carregando notícias...",
    "news.noNews": "Nenhuma notícia disponível",
    "language.title": "Idioma",
    "language.subtitle": "Escolha seu idioma preferido",
    "language.select": "Selecionar Idioma",
    "language.save": "Salvar Preferência",
    "language.saved": "Preferência de idioma salva!",
    "common.loading": "Carregando...",
    "common.error": "Ocorreu um erro",
    "common.retry": "Tentar Novamente",
    "common.close": "Fechar",
    "auth.loginRequired": "Login Necessário",
    "auth.pleaseLogin": "Faça login para continuar",
  },
  ru: {
    "nav.home": "Главная",
    "nav.signals": "Сигналы",
    "nav.pricing": "Цены",
    "nav.login": "Войти",
    "nav.logout": "Выйти",
    "nav.portfolio": "Портфель",
    "nav.news": "Новости",
    "nav.history": "Напоминание",
    "nav.language": "Язык",
    "nav.admin": "Админ панель",
    "home.title": "CryptoBit",
    "home.subtitle": "Отслеживайте цены криптовалют в реальном времени",
    "home.allAssets": "Все активы",
    "home.gainers": "Растущие",
    "home.losers": "Падающие",
    "home.search": "Поиск монет...",
    "home.rank": "#",
    "home.name": "Название",
    "home.price": "Цена",
    "home.change24h": "Изменение за 24ч",
    "home.marketCap": "Рыночная кап.",
    "home.previous": "Назад",
    "home.next": "Вперед",
    "home.page": "Страница",
    "home.of": "из",
    "portfolio.title": "Портфель",
    "portfolio.subtitle": "Отслеживайте ваши криптоактивы",
    "portfolio.addAsset": "Добавить актив",
    "portfolio.totalValue": "Общая стоимость",
    "portfolio.change24h": "Изменение за 24ч",
    "portfolio.totalPnL": "Общая прибыль/убыток",
    "portfolio.yourHoldings": "Ваши активы",
    "portfolio.noAssets": "Пока нет активов",
    "portfolio.addFirst": "Начните создавать портфель",
    "portfolio.addFirstAsset": "Добавить первый актив",
    "portfolio.editAsset": "Редактировать актив",
    "portfolio.quantity": "Количество",
    "portfolio.buyPrice": "Цена покупки (USD)",
    "portfolio.cancel": "Отмена",
    "portfolio.save": "Сохранить",
    "portfolio.saving": "Сохранение...",
    "portfolio.searchCoins": "Поиск монет...",
    "portfolio.loginRequired": "Требуется вход",
    "portfolio.loginToAccess": "Войдите для доступа к портфелю",
    "portfolio.loginToContinue": "Войти",
    "signals.title": "Торговые сигналы",
    "signals.subtitle": "Получайте профессиональные сигналы",
    "signals.free": "Бесплатные сигналы",
    "signals.pro": "Pro сигналы",
    "signals.entry": "Вход",
    "signals.stopLoss": "Стоп-лосс",
    "signals.takeProfit": "Тейк-профит",
    "signals.leverage": "Плечо",
    "signals.upgradeToSee": "Обновите до PRO",
    "signals.noSignals": "Нет доступных сигналов",
    "pricing.title": "Обновить до Pro",
    "pricing.subtitle": "Получите доступ к премиум сигналам",
    "pricing.perMonth": "/месяц",
    "pricing.features": "Возможности",
    "pricing.scanQR": "Сканируйте QR для оплаты",
    "pricing.uploadScreenshot": "Загрузить скриншот оплаты",
    "pricing.submit": "Отправить платеж",
    "news.title": "Крипто новости",
    "news.subtitle": "Последние новости и обновления",
    "news.readMore": "Читать далее",
    "news.loading": "Загрузка новостей...",
    "news.noNews": "Нет новостей",
    "language.title": "Язык",
    "language.subtitle": "Выберите предпочитаемый язык",
    "language.select": "Выбрать язык",
    "language.save": "Сохранить настройки языка",
    "language.saved": "Настройки языка сохранены!",
    "common.loading": "Загрузка...",
    "common.error": "Произошла ошибка",
    "common.retry": "Повторить",
    "common.close": "Закрыть",
    "auth.loginRequired": "Требуется вход",
    "auth.pleaseLogin": "Войдите для продолжения",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.signals": "الإشارات",
    "nav.pricing": "الأسعار",
    "nav.login": "تسجيل الدخول",
    "nav.logout": "تسجيل الخروج",
    "nav.portfolio": "المحفظة",
    "nav.news": "الأخبار",
    "nav.history": "تذكير التاريخ",
    "nav.language": "اللغة",
    "nav.admin": "لوحة الإدارة",
    "home.title": "CryptoBit",
    "home.subtitle": "تتبع أسعار العملات المشفرة في الوقت الفعلي",
    "home.allAssets": "جميع الأصول",
    "home.gainers": "الرابحون",
    "home.losers": "الخاسرون",
    "home.search": "بحث عن العملات...",
    "home.rank": "#",
    "home.name": "الاسم",
    "home.price": "السعر",
    "home.change24h": "التغير 24س",
    "home.marketCap": "القيمة السوقية",
    "home.previous": "السابق",
    "home.next": "التالي",
    "home.page": "صفحة",
    "home.of": "من",
    "portfolio.title": "المحفظة",
    "portfolio.subtitle": "تتبع أصولك المشفرة",
    "portfolio.addAsset": "إضافة أصل",
    "portfolio.totalValue": "القيمة الإجمالية",
    "portfolio.change24h": "التغير 24س",
    "portfolio.totalPnL": "إجمالي الربح/الخسارة",
    "portfolio.yourHoldings": "أصولك",
    "portfolio.noAssets": "لا توجد أصول بعد",
    "portfolio.addFirst": "ابدأ ببناء محفظتك",
    "portfolio.addFirstAsset": "أضف أصلك الأول",
    "portfolio.editAsset": "تعديل الأصل",
    "portfolio.quantity": "الكمية",
    "portfolio.buyPrice": "سعر الشراء (USD)",
    "portfolio.cancel": "إلغاء",
    "portfolio.save": "حفظ",
    "portfolio.saving": "جارٍ الحفظ...",
    "portfolio.searchCoins": "بحث عن العملات...",
    "portfolio.loginRequired": "تسجيل الدخول مطلوب",
    "portfolio.loginToAccess": "سجل الدخول للوصول إلى محفظتك",
    "portfolio.loginToContinue": "تسجيل الدخول",
    "signals.title": "إشارات التداول",
    "signals.subtitle": "احصل على إشارات تداول احترافية",
    "signals.free": "إشارات مجانية",
    "signals.pro": "إشارات برو",
    "signals.entry": "الدخول",
    "signals.stopLoss": "وقف الخسارة",
    "signals.takeProfit": "جني الأرباح",
    "signals.leverage": "الرافعة",
    "signals.upgradeToSee": "قم بالترقية لـ PRO لرؤية هذه الإشارة",
    "signals.noSignals": "لا توجد إشارات",
    "pricing.title": "الترقية إلى برو",
    "pricing.subtitle": "احصل على إشارات بريميوم",
    "pricing.perMonth": "/شهر",
    "pricing.features": "الميزات",
    "pricing.scanQR": "امسح QR للدفع",
    "pricing.uploadScreenshot": "رفع لقطة شاشة الدفع",
    "pricing.submit": "إرسال الدفع",
    "news.title": "أخبار الكريبتو",
    "news.subtitle": "آخر الأخبار والتحديثات",
    "news.readMore": "اقرأ المزيد",
    "news.loading": "جارٍ تحميل الأخبار...",
    "news.noNews": "لا توجد أخبار",
    "language.title": "اللغة",
    "language.subtitle": "اختر لغتك المفضلة",
    "language.select": "اختر اللغة",
    "language.save": "حفظ تفضيل اللغة",
    "language.saved": "تم حفظ تفضيل اللغة!",
    "common.loading": "جارٍ التحميل...",
    "common.error": "حدث خطأ",
    "common.retry": "إعادة المحاولة",
    "common.close": "إغلاق",
    "auth.loginRequired": "تسجيل الدخول مطلوب",
    "auth.pleaseLogin": "سجل الدخول للمتابعة",
  },
  tr: {
    "nav.home": "Ana Sayfa",
    "nav.signals": "Sinyaller",
    "nav.pricing": "Fiyatlandırma",
    "nav.login": "Giriş",
    "nav.logout": "Çıkış",
    "nav.portfolio": "Portföy",
    "nav.news": "Haberler",
    "nav.history": "Geçmiş Hatırlatıcı",
    "nav.language": "Dil",
    "nav.admin": "Yönetici Paneli",
    "home.title": "CryptoBit",
    "home.subtitle": "Kripto para fiyatlarını gerçek zamanlı takip edin",
    "home.allAssets": "Tüm Varlıklar",
    "home.gainers": "Yükselenler",
    "home.losers": "Düşenler",
    "home.search": "Coin ara...",
    "home.rank": "#",
    "home.name": "İsim",
    "home.price": "Fiyat",
    "home.change24h": "24s Değişim",
    "home.marketCap": "Piyasa Değeri",
    "home.previous": "Önceki",
    "home.next": "Sonraki",
    "home.page": "Sayfa",
    "home.of": "/",
    "portfolio.title": "Portföy",
    "portfolio.subtitle": "Kripto varlıklarınızı takip edin",
    "portfolio.addAsset": "Varlık Ekle",
    "portfolio.totalValue": "Toplam Değer",
    "portfolio.change24h": "24s Değişim",
    "portfolio.totalPnL": "Toplam Kar/Zarar",
    "portfolio.yourHoldings": "Varlıklarınız",
    "portfolio.noAssets": "Henüz varlık yok",
    "portfolio.addFirst": "Portföyünüzü oluşturmaya başlayın",
    "portfolio.addFirstAsset": "İlk Varlığınızı Ekleyin",
    "portfolio.editAsset": "Varlığı Düzenle",
    "portfolio.quantity": "Miktar",
    "portfolio.buyPrice": "Alış Fiyatı (USD)",
    "portfolio.cancel": "İptal",
    "portfolio.save": "Kaydet",
    "portfolio.saving": "Kaydediliyor...",
    "portfolio.searchCoins": "Coin ara...",
    "portfolio.loginRequired": "Giriş Gerekli",
    "portfolio.loginToAccess": "Portföyünüze erişmek için giriş yapın",
    "portfolio.loginToContinue": "Giriş Yap",
    "signals.title": "Ticaret Sinyalleri",
    "signals.subtitle": "Profesyonel sinyaller alın",
    "signals.free": "Ücretsiz Sinyaller",
    "signals.pro": "Pro Sinyaller",
    "signals.entry": "Giriş",
    "signals.stopLoss": "Stop Loss",
    "signals.takeProfit": "Take Profit",
    "signals.leverage": "Kaldıraç",
    "signals.upgradeToSee": "Bu sinyali görmek için PRO'ya yükseltin",
    "signals.noSignals": "Sinyal yok",
    "pricing.title": "Pro'ya Yükselt",
    "pricing.subtitle": "Premium sinyallere erişin",
    "pricing.perMonth": "/ay",
    "pricing.features": "Özellikler",
    "pricing.scanQR": "Ödeme için QR'ı Tarayın",
    "pricing.uploadScreenshot": "Ödeme Ekran Görüntüsü Yükle",
    "pricing.submit": "Ödemeyi Gönder",
    "news.title": "Kripto Haberleri",
    "news.subtitle": "Son haberler ve güncellemeler",
    "news.readMore": "Devamını Oku",
    "news.loading": "Haberler yükleniyor...",
    "news.noNews": "Haber yok",
    "language.title": "Dil",
    "language.subtitle": "Tercih ettiğiniz dili seçin",
    "language.select": "Dil Seçin",
    "language.save": "Dil Tercihini Kaydet",
    "language.saved": "Dil tercihi kaydedildi!",
    "common.loading": "Yükleniyor...",
    "common.error": "Bir hata oluştu",
    "common.retry": "Tekrar Dene",
    "common.close": "Kapat",
    "auth.loginRequired": "Giriş Gerekli",
    "auth.pleaseLogin": "Devam etmek için giriş yapın",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("cryptobit-language");
      if (saved && saved in translations) {
        return saved as LanguageCode;
      }
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("cryptobit-language", language);
    document.documentElement.lang = language;
    if (language === "ar") {
      document.documentElement.dir = "rtl";
    } else {
      document.documentElement.dir = "ltr";
    }
  }, [language]);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
